config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :todos, except: :show
  resources :todo_list_positions, only: :update

  namespace :admin do
    resources :users
    resources :services
    resources :announcements
    resources :notifications

    root to: "users#index"
  end
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'todos#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/service-worker.js' => "service_worker#service_worker"
  get '/manifest.json' => "service_worker#manifest"
  get '/offline.html' => "service_worker#offline"

  get '/:date', to: 'todos#index', as: :date
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :user

  validates_presence_of :title
  
  scope :incomplete, -> { where(completed_at: nil) }
  scope :complete, -> { where.not(completed_at: nil) }

  def due_on
    due_at.to_date
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    @date = Date.parse(params[:date]) rescue Date.current
    @todos = current_user.todos.where(due_at: @date.beginning_of_day..@date.end_of_day).order(position: :asc)
    @todo ||= @todos.new(due_at: @date.end_of_day)
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = current_user.todos.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = current_user.todos.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to date_path(date: @todo.due_on), notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to date_path(date: @todo.due_on), notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
        format.js   { head :ok }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to date_path(date: @todo.due_on), notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = current_user.todos.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.require(:todo).permit(:title, :user_id, :due_at, :completed_at, :position)
    end
end

app/helpers/todos_helper.rb
# frozen_string_literal: true

module TodosHelper
  def due_in_less_than_class(todo)
    base = 'due-in-less-than'
    if todo.due_at < 1.hour.from_now
      "#{base}-an-hour"
    elsif todo.due_at < 2.hours.from_now
      "#{base}-two-hours"
    elsif todo.due_at < 4.hours.from_now
      "#{base}-four-hours"
    else
      ''
    end
  end

  def overdue_ago_class(todo)
    'overdue-less-than-one-hour-ago'
  end
end

app/views/todos/_card.html.erb
<div
  data-id="<%= todo.id %>"
  data-controller="revealable"
  data-action="click->revealable#reveal"
  class="todo-row <%= todo.completed_at? ? 'todo-row-completed' : 'todo-row-incomplete' %>"
>
  <div style="display: flex; flex-direction: row; align-items: center; margin-left: -18px;">
    <div class="handle" style="cursor: grab; color: transparent; height: 30px; width: 30px; min-width: 30px;" data-target="revealable.colorable">
      <%= render 'icons/three_dots_vertical' %>
    </div>
    <span class="todo-title" style="flex-grow: 1;">
      <%= todo.title %>
      <% if !todo.completed_at? %>
        <br>
        <% if (Time.current..4.hours.from_now).cover? todo.due_at %>
          <span class="due-in-time <%= due_in_less_than_class(todo) %>">due in <%= time_ago_in_words(todo.due_at) %></span>
        <% elsif (1.hour.ago..Time.current).cover? todo.due_at %>
          <span class="due-in-time <%= overdue_ago_class(todo) %>">overdue <%= time_ago_in_words(todo.due_at) %> ago</span>
        <% end %>
      <% end %>
    </span>
    <%= button_tag 'edit',
                   class: 'btn btn-link btn-sm',
                   style: 'visibility: hidden;',
                   data: {
                     reflex: "click->TodosReflex#edit",
                     target: 'revealable.hidable',
                     id: todo.id
                   }
    %>
    <%= check_box_tag nil, nil,
                      todo.completed_at?,
                      class: 'ml-2',
                      style: 'visibility: hidden;',
                      data: {
                        reflex: "click->TodosReflex#toggle_completed_at",
                        target: 'revealable.hidable',
                        id: todo.id
                      }
    %>
  </div>
</div>

app/views/todos/_date_nav.html.erb
<div id="date-nav" data-controller="revealable" data-action="click->revealable#reveal">
  <%= link_to date_path(date: date - 10.years), id: 'prev-decade', style: 'color: transparent;', data: { target: 'revealable.colorable' } do %>
    <%= render 'icons/chevron_double_left' %>
  <% end %>
  <%= link_to date_path(date: date - 1.year), id: 'prev-year', style: 'color: transparent;', data: { target: 'revealable.colorable' } do %>
    <%= render 'icons/chevron_left' %>
  <% end %>
  <%= link_to date_path(date: date - 3.months), id: 'prev-quarter', style: 'color: transparent;', data: { target: 'revealable.colorable' } do %>
    <%= render 'icons/chevron_double_left' %>
  <% end %>
  <%= link_to date_path(date: date - 1.month), id: 'prev-month', style: 'color: transparent;', data: { target: 'revealable.colorable' } do %>
    <%= render 'icons/chevron_left' %>
  <% end %>
  <%= link_to date_path(date: date - 1.week), id: 'prev-week', style: 'color: transparent;', data: { target: 'revealable.colorable' } do %>
    <%= render 'icons/chevron_double_left' %>
  <% end %>
  <%= link_to date_path(date: date.prev_day), id: 'prev-day', style: 'color: transparent;', data: { target: 'revealable.colorable' } do %>
    <%= render 'icons/chevron_left' %>
  <% end %>

  <span id="this-month"><%= date.strftime('%b') %></span>
  <span id="this-day"><%= date.strftime('%e %a') %></span>
  <span id="this-year"><%= date.strftime('%Y') %></span>

  <%= link_to date_path(date: date.next_day), id: 'next-day', style: 'color: transparent;', data: { target: 'revealable.colorable' } do %>
    <%= render 'icons/chevron_right' %>
  <% end %>
  <%= link_to date_path(date: date + 1.week), id: 'next-week', style: 'color: transparent;', data: { target: 'revealable.colorable' } do %>
    <%= render 'icons/chevron_double_right' %>
  <% end %>
  <%= link_to date_path(date: date + 1.month), id: 'next-month', style: 'color: transparent;', data: { target: 'revealable.colorable' } do %>
    <%= render 'icons/chevron_right' %>
  <% end %>
  <%= link_to date_path(date: date + 3.months), id: 'next-quarter', style: 'color: transparent;', data: { target: 'revealable.colorable' } do %>
    <%= render 'icons/chevron_double_right' %>
  <% end %>
  <%= link_to date_path(date: date + 1.year), id: 'next-year', style: 'color: transparent;', data: { target: 'revealable.colorable' } do %>
    <%= render 'icons/chevron_right' %>
  <% end %>
  <%= link_to date_path(date: date + 10.years), id: 'next-decade', style: 'color: transparent;', data: { target: 'revealable.colorable' } do %>
    <%= render 'icons/chevron_double_right' %>
  <% end %>
</div>

app/views/todos/_form.html.erb
<%= form_with(model: todo, local: true, html: { data: { controller: 'todo-form' } }) do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation">
      <% todo.errors.full_messages.each_with_index do |message, index| %>
        <% unless index == 0 %>
          <br>
        <% end %>
        <%= message %>
      <% end %>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :title,
                        placeholder: 'Add a new todo ...',
                        class: 'form-control',
                        data: {
                          target: 'todo-form.titleInput',
                          action: 'keyup->todo-form#toggleShow',
                          reflex: "change->TodosReflex#validate",
                        }
    %>
  </div>

  <div class="form-group"
       style="display: flex; flex-direction: row; justify-content: space-between; visibility: <%= form.object.title? ? 'visible' : 'hidden' %>"
       data-target="todo-form.dueAtSelect">
    <%= form.datetime_select :due_at, {}, { class: 'form-control' } %>
  </div>

  <div class="form-group"
       style="display: flex; flex-direction: row; justify-content: space-between; visibility: <%= form.object.title? ? 'visible' : 'hidden' %>""
       data-target="todo-form.actionsDiv">
    <%= link_to "Cancel", '#', class: "btn btn-link", data: { reflex: "TodosReflex#reset" } %>

    <% if todo.persisted? %>
      <%= link_to 'Destroy', todo, method: :delete, class: "btn btn-outline-danger", data: { confirm: 'Are you sure?' } %>
    <% end %>

    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1>Edit Todo</h1>

<%= render 'form', todo: @todo %>

app/views/todos/index.html.erb
<%= render 'date_nav', date: @date %>

<%= render 'form', todo: @todo %>

<div
  data-controller="drag-drop-sortable"
  data-drag-drop-sortable-model-name="todo_list_position"
  data-drag-drop-sortable-url="/todo_list_positions/:id.js"
>
  <% (@todos.incomplete + @todos.complete).each do |todo| %>
    <%= render 'card', todo: todo %>
  <% end %>
</div>

<% if @todos.empty? %>
  <%= image_tag image_urls.sample, style: "width: 100%" %>
<% end %>

app/views/todos/new.html.erb
<h1>New todo</h1>

<%= render 'form', todo: @todo %>

app/views/todos/show.html.erb
<div class="page-header">
  <%= link_to todos_path, class: 'btn btn-default' do %>
    All Todos
  <% end %>
  <%= link_to edit_todo_path(@todo), class: 'btn btn-primary' do %>
    Edit
  <% end %>
  <h1>Show todo</h1>
</div>

<dl class="dl-horizontal">
  <dt>Title:</dt>
  <dd><%= @todo.title %></dd>

  <dt>User:</dt>
  <dd><%= @todo.user %></dd>

  <dt>Due at:</dt>
  <dd><%= @todo.due_at %></dd>

  <dt>Completed at:</dt>
  <dd><%= @todo.completed_at %></dd>

  <dt>Position:</dt>
  <dd><%= @todo.position %></dd>

</dl>